=== Musica




=== ((Ukulele))
Accordi ukulele – Maggiori

[options="header", cols="3,1,1,1"]
|========= 
| Nota | 1 | 2 | 3 
| C (Do) | 0·0·0·3 | 0·4·0·3 | 0·7·8·7 | 
D (Re) | 2·2·2·0 | 2·2·2·5 | 7·6·5·0 |
E (Mi) | 4·4·4·2 |  4·4·0·2 | 4·4·4·7 | 
F (Fa) | 2·0·1·0 |  5·5·5·0 | 5·5·5·8 | 
G (Sol) | 0·2·3·2 |  0·2·3·5 | 0·7·7·5 | 
A (La) | 2·1·0·0 |  6·4·5·0 (Peppa Pig) | 2·4·0·4 | 
B (Si) |  4·3·2·2 | 4·3·2·6 | 8·6·7·9 | 
Cm (Do minore) | 0·3·3·3 | 0·7·8·6 | 0·0·11·12 | 
Dm (Re minore) | 2·2·1·0 | 7·5·5·0 | 9·9·8·7 | 
Em (Mi minore) | 0·4·0·2 | 4·4·3·2 | 0·7·7·7 | 
Fm (Fa minore) | 1·0·1·3 | 5·5·4·3 | 5·5·8·8 | 
Gm (Sol minore) | 0·2·3·1 | 0·7·6·5 | 0·7·6·10 |
Am (La minore) | 2·0·0·0 | 2·4·5·0 (Powerchord) | 7·9·8·7 | 
Bm (Si minore) | 4·2·2·2 | 4·6·7·5 | 7·6·7·5 | 
|========= 

==== Esercizi Strumming

.Nomenclatura
|====
| u | up, mezza battuta  | d | down, mezza battuta 
| U | up, una battuta | D | down, una battuta 
| u+ | up, 3/4 di battuta  | d+ | down, 3/4 di battuta  
| u- | up, 1/4 di battuta  | d- | down, 1/4 di battuta 
| . | 1/2 di battuta senza gesti | |
|====


.4/4
|====
| basic | D | D | D | D
| standard | u d | u d | u d | u d
| swing | u+ d- | u+ d-| u+ d-| u+ d-
| church | D | d U | D | d U 
| calipso | d . | d u | . u | d .
| standard | u | u d | u | ud
|====

.3/4
|====
| u | u d | | ud
|====

==== Arpeggi

.Nomenclatura
|====
| p1 | pollice corda 1 footnote:[la prima a sx nelle tablature]
| p2 | pollice corda 2
| 13 | indice corda 3
| 24 | indice corda 4
|====

.Arpeggi
|====
| base  | 1 2 3 4
| alternato | 1 3 2 4
| mike1 | 1 3 4 3 - 2 3 4 3
|====

.((Progressione I I7 IV V7))
[format="csv", options="header"]
|===
I, ii, iii, IV, V, vi, vii
C, D, E, F, G, A, B
FL, G, A, Bb, C, D, E
G, A, B, C, D, E, F#
A, B, C#, D, E, F#, G#
D, E, F#, G, A, B, C#
|===


=== Songs

((A children's lullaby)) footnote:[https://youtu.be/XyfPJ6JNlfU?list=PLR-lgQYwrszE55v7gWoYm-FsWH5Mps4xW]:: Progressione I V7, Tonalità C +
4/4 Pattern C G7 C G7

((Amazing Grace)) footnote:[https://youtu.be/Zj-xa9sLNyY?list=PLR-lgQYwrszE55v7gWoYm-FsWH5Mps4xW]:: Progressione I I7 IV V7, Tonalità C +
4/4 pattern C C7 F C/C7 | F C C G7/C

((Fra' Martino)):: *Note* C 

((London Bridge)):: Progressione I V7, Tonalità C +
4/4 pattern C C G7 C

You're my sunshine footnote:[https://youtu.be/dnA3T8uuuoY?list=PLR-lgQYwrszE55v7gWoYm-FsWH5Mps4xW]:: da fare

((Se sei felice e tu lo sai))footnote:[https://youtu.be/elTDFX9r_9k?list=PLR-lgQYwrszE55v7gWoYm-FsWH5Mps4xW]:: 4/4 pattern:  G D7 D7 G | C G D7 G


.Risorse utili da cui ho tratto le info di questo capitolo
* https://www.youtube.com/user/MusicTeacher2010/
* 